### ISSUE TITLE
Multiple input boxes (possibly with MathQuill)

### ISSUE THREAD

**Issue by pstaabp** [openwebwork/webwork3#67]
This is under the problem-set-work branch (I'll test main too.)
Under the LibraryBrowser -> Open Problem Library -> Subj: algebra -> Ch: functions -> sect: domain and range

The first problem (which is file_path: `Library/ma117DB/set3/srw2_1_49.pg` ) has extra input boxes.  Here's what I see:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/879338/142290769-a60ffdbe-f973-4f87-862a-d2e847776930.png">

The rest of these seem to render normally.   The first one has Mathquill boxes.  

If I load the above problem in the ProblemViewer, it renders with the proper number of input boxes.

**Comment by drdrew42** [comment]
This is due to problems being rendered with the same `answerPrefix` -- the id is not being properly interpreted when the problem object is created or the answerPrefix is using a default value, or something else along those lines.
